### ISSUE TITLE
SSL Certificate/Private Key not found!

### ISSUE THREAD

**Issue by artofka** [0x3333/smbpasswd-web#13]
I'm newbie with ssl.

Got the error after trying to start server:
```
./app.py server --ssl
SSL Certificate/Private Key not found!

```

 I did SA certificate but command still won't work. Thanks for help!

**Comment by 0x3333** [comment]
Hi. when you provide just the `--ssl` parameter, it will check in the default location for the certificate and the pk.

```
  --ssl-cert SSL_CERT   SSL certificate to use (default: res/fullchain.pem)
  --ssl-key SSL_KEY     SSL certificate private key (default: res/privkey.pem)
```

Which is `res/fullchain.pem` and `res/privkey.pem`, if your files are not in this directory, you should provide the `--ssl-cert` and `--ssl-key` parameters with the path to them.
