### ISSUE TITLE
Setup Guide for Apache/Nginx

### ISSUE THREAD

**Issue by DumpName** [0x3333/smbpasswd-web#16]
I just rediscovered this project while maintaining one of my servers.
In the past was a hint saying that the app should be deployed behind a webserver (apache2/nginx) if I remember correctly.
As my serverside setup has changed since my inital deployment a setup with an apache webserver would be nice to have.
However, since I haven't had a chance to learn Python deployment practices, or anything python related, yet,  a little setup guide would be helpful at this point.

**Comment by 0x3333** [comment]
A docker would fit your needs?

**Comment by 0x3333** [comment]
Technically speaking, you can start the app(`./app.py`) and just create a reverse proxy to it. Like: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by DumpName** [comment]
Sadly I do not have a docker environment setup yet. However this might follow later (after some changes in my hardware stack).
Will try the proxy setup. Sometimse one is just to stupid to google propper.
