### ISSUE TITLE
Passwords should not be logged by default

### ISSUE THREAD

**Issue by JoseGoncalves** [0x3333/smbpasswd-web#3]
After setting up smbpasswd-web as a systemd service with stdout and stderr redirected to syslog, I've noticed that every API request to the server is logged. I think this should not be the default, but something that could be enabled in a config file as a debug mode. My main concern is security, as the passwords that a samba user sets appear in clear text in my syslog file. Example of such entries:
```
127.0.0.1 - - [04/Feb/2020 12:15:42] "GET /api/set_password/<token>/<password> HTTP/1.1" 200 -
```

**Comment by 0x3333** [comment]
Yeah, it sucks big time, actually, I should send the password as POST, I'll change that, and then, disable http server logging. I'll work on that.

**Comment by 0x3333** [comment]
Fixed the issues. If you pass `--verbose` it will log the requests, otherwise, nothing will be logged. Also, I changed the requests to use POST instead of GET. And the server output is validated. Should fix all your problems.

**Comment by JoseGoncalves** [comment]
Hi @0x3333. Your update broke the gen-token app. When I try to generate a token I get this:

```sh
$ ./app.py gen-token user
Traceback (most recent call last):
  File "./app.py", line 248, in <module>
    main()
  File "./app.py", line 227, in main
    _verbose = _args.verbose
AttributeError: 'Namespace' object has no attribute 'verbose'
```

**Comment by 0x3333** [comment]
Fixed, my bad.
