### ISSUE TITLE
Use FQDN instead of hostname

### ISSUE THREAD

**Issue by DumpName** [0x3333/smbpasswd-web#5]
Hi,
i don't know if you had this already in mind as I saw your TODO in the code. However it would be nice if it would be possible to use socket.getfqdn() instead of the hostname.

**Comment by 0x3333** [comment]
Nice catch. Fixed.

**Comment by 0x3333** [comment]
I also added another change, using `gen-token --fqdn SOMETHING.ELSE`, will override the default `getfqdn()`.
